### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by daviddeejjames** [daviddeejjames/wp-netlify-build#4]

**Comment by Jitsusama** [comment]
I wouldn't mind helping out on this. Do you have any specific license in mind? I generally use Apache 2.0, because most of the stuff I Open Source I don't mind being re-integrated into commercial products. That said, if you want to make sure that your software is only integrated with other OSS projects, then GPL might be a good choice.

**Comment by daviddeejjames** [comment]
I think WordPress plugins tend to use GPL so lets go with that :) 👍

**Comment by Jitsusama** [comment]
LOL, if it makes you feel any better, I at least am familiar with PHP, even if not with WordPress :laughing:

**Comment by daviddeejjames** [comment]
@Jitsusama merged! thanks for this
